notifications:
  email: false

language: cpp

# if pull request: always build
# if push: only build for master branch
if: (type != push) OR (type = push AND branch = master)

matrix:
  include:
    - os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - libasound2-dev
            - libxcursor-dev
            - libxinerama-dev
            - libxrandr-dev
            - cmake
      env: run=bash
    - os: osx
      osx_image: xcode9.4
      env: run=sh
    - os: windows
      env: run=sh

install:
  # upgrade cmake
  - |
    if [[ $TRAVIS_OS_NAME == 'linux' ]]; then
      echo "Upgrading CMake"
      DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
      mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
      travis_retry wget --no-check-certificate https://github.com/Kitware/CMake/releases/download/v3.18.0-rc3/cmake-3.18.0-rc3.tar.gz
      tar -xvf cmake-3.18.0-rc3.tar.gz > /dev/null
      mv cmake-3.18.0-rc3 cmake-install
      PATH=${DEPS_DIR}/cmake-install:4{DEPS_DIR}/cmake-install/bin:$PATH
      cd ${TRAVIS_BUILD_DIR}
    fi

script:
  - cmake --version
  - mkdir build && cd build/
  - cmake ..
  - cmake --build . --config Release

  # Validate
  -  cd ${TRAVIS_BUILD_DIR}
  - $run validate.sh
